build:
    tests:
        override: 
            - 
                command: 'rubocop'
                analysis:
                    file: 'data'
                    format: 'rubocop'
tools:
    rubocop: true
