build:
    tests:
        override: 
            - 
                command: 'rubocop .'
                analysis:
                    file: 'something'
                    format: 'rubocop'
tools:
    external_analysis: 
        enabled: true
        runs: 10
