tools:
    external_analysis: true
build:
    tests:
        before:
            - gem install rubocop
        override: 
            - 
                command: 'rubocop -o data'
                analysis:
                    file: 'data'
                    format: 'rubocop'

